### ISSUE TITLE
Review: Pricing and FAQ

### ISSUE THREAD

**Issue by sanehirakenji** [volunthree/volunthree#100]
## Review Branch

review-pricing-and-faq

## Files to review

* Pricing.jsx
* FAQ.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

3/4/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by sanehirakenji** [comment]
Pricing.jsx:
- Design-08: Can potentially refactor the form checks that contain the data on the different branches in order to shorten the code.
- JS-08: Incorrect usage of JSDoc Comment.



FAQ.jsx:
- Will need to review upon the style change, but for now follows all checklist requirements.

**Comment by kairemUH** [comment]
## Pricing.jsx

Looks good to me. Perhaps more comments describing parts of the page could be nice but I don't think is necessary.

## FAQ.jsx

- JS-08 @ Line 5:  Turn comment into JSdoc comment

**Comment by tylerz1443** [comment]
##Pricing.jsx##
It looks fine, there may need to have comments about all of the forms and what they are for, or have variable names that are easily identifiable for the forms.  

##FAQ.jsx##
-JS-08: Line 5, convert comment into jsdoc comment

**Comment by ian-lastname** [comment]
Pricing.jsx
- Looks fine, comments would be helpful though. 

FAQ.jsx
- JS-08: @ line 5, turn comment into JSdoc comment.

**Comment by tevin-takata** [comment]
## Pricing.jsx

n/a

## FAQ.jsx

JS-08 @ Line 5: Turn comment into JSdoc comment
Update
