### ISSUE TITLE
Review: Contact Us and FAQ

### ISSUE THREAD

**Issue by sanehirakenji** [volunthree/volunthree#118]
## Review Branch

Both the contact us page and FAQ page were reworked, so this review will focus on those two.

review-contact-us-and-faq

## Files to review

* ContactUs.jsx
* FAQ.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

3/11/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by sanehirakenji** [comment]
**ContactUs.jsx:**
- Design-01/07: Should refactor the header with voluntree background around site as well as the accordion items for less confusion when reading.
- JS-08: Create a JSDoc comment for this page.



**FAQ.jsx:**
- JS-08: Create a JSDoc comment for this page.

**Comment by kairemUH** [comment]
## ContactUs.jsx:

- JS-08: Add a JSDoc comment describing the page.

## FAQ.jsx:

- JS-08: Same thing. Make a JSDoc comment.

Lgtm!

**Comment by tylerz1443** [comment]
##ContactUs.jsx##
- JS-08: Create a JSDoc comment

##FAQ.jsx##
- JS-08: Create a JSDoc comment

**Comment by ian-lastname** [comment]
### FAQ.jsx
- Js-08: Create JSDoc comment that describes page.

### ContactUs.jsx
- Js-08: Create JSDoc comment that describes page.

**Comment by jgaleria** [comment]
ContactUs.jsx: 
- JS-08: Add javadoc comment

FAQ.jsx:: 
- JS-08: Add javadoc comment

**Comment by tevin-takata** [comment]
## ContactUs.jsx:

JS-08: Add a JSDoc comment.

## FAQ.jsx:

JS-08: Add a JSDoc comment.
