### ISSUE TITLE
Review: Message Log and Contacts List

### ISSUE THREAD

**Issue by sanehirakenji** [volunthree/volunthree#119]
## Review Branch

review-message-log-and-contacts-list

## Files to review

* MessageLog.jsx
* ContactsList.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

3/25/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by sanehirakenji** [comment]
MessageLog.jsx:
- JS-08: Create a JSDoc comment for this page.

ContactsList.jsx:
- JS-08: Create a JSDoc comment for this page.

**Comment by kairemUH** [comment]
## MessageLog.jsx:

JS-08: Add a JSDoc comment describing the page.

## ContactsList.jsx:

JS-08: Same thing. Just add a jsdoc comment.

Overall both files look great!

**Comment by tylerz1443** [comment]
## MessageLog.jsx

- JS-08: Add a JSDoc comment about page

## ContactsList.jsx

- JS-08: Add a JSDoc comment about page

**Comment by jgaleria** [comment]
MessageLog.jsx
- JS-08: Add JSDoc comment about page functionality. 

ContactList.jsx
- JS-08: Add JSDoc comment about page functionality/

**Comment by ian-lastname** [comment]
### MessageLog.jsx
- JS-08: Add JSDoc comment 

### ContactList.jsx
- JS-08: Ass JSDoc comment

**Comment by tevin-takata** [comment]
## MessageLog.jsx:

JS-08: JSDoc comment

## ContactsList.jsx:

JS-08: JSDoc comment

Same as usual haha
