### ISSUE TITLE
Review: Profile and Edit Profile Pages

### ISSUE THREAD

**Issue by sanehirakenji** [volunthree/volunthree#122]
## Review Branch

review-profile-and-edit-profile

## Files to review

* Profile.jsx
* EditProfile.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

4/1/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by kairemUH** [comment]
## EditProfile.jsx:

JS-08: Add JSDoc comment describing the page

## Profile.jsx:

JS-08: Same as other file. Add JDDoc comment.
Design-01: Could turn sections of a profile into its own component (not for modularity but for reusability).

**Comment by tylerz1443** [comment]
## EditProfile.jsx
- JS-08: Add jsdoc comment for the page

## Profile.jsx
- Design-01: create separate components for the profile page, some of the info on the card might be able to use in other part of the site
- JS-08: Add jsdoc comment for the page

**Comment by ian-lastname** [comment]
### EditProfile.jsx
- JS-08: Add jsdoc comment for the page explaining its purpose.

### Profile.jsx
- JS-08: Add jsdoc comment for the page explaining its purpose.
- D-01: Can create separate components for the profile page for added readability.

**Comment by tevin-takata** [comment]
## Profile.jsx:

Design-01: Each individual section of the profile page can likely be converted into a component for readability
JS-08: Create a JSDoc comment for this page.

## EditProfile.jsx:

JS-08: Create a JSDoc comment for this page.
