### ISSUE TITLE
Review: User Dashboard and Individuals in need of Service

### ISSUE THREAD

**Issue by sanehirakenji** [volunthree/volunthree#131]
## Review Branch

review-user-dash-individuals-in-need

## Files to review

* UserDashboard.jsx
* IndividualsInNeedOfService.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

4/8/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by sanehirakenji** [comment]
**UserDashboard.jsx:**
- JS-08: Update the JSDoc comment to fit the page contents.

**IndividualsInNeedOfService.jsx:**
- Design-01: Can refactor the events area in order to reduce duplication in the page.
- JS-08: Create a JSDoc comment for this page.

**Comment by tylerz1443** [comment]
## UserDashboard.jsx
- JS-08: update jsdoc comment

## IndividualsInNeedOfService.jsx
- JS-08: make jsdoc comment

**Comment by ian-lastname** [comment]
## UserDashboard.jsx
- JS-08: Update JSDoc comment to accommodate for page contents.

## IndividualsInNeedOfService.jsx:
- JS-08: Make JSDoc comment

**Comment by jgaleria** [comment]
UserDashboard.jsx
- JS-08 Update JSDoc comment for page
IndividualsInNeedOfService.jsx
- JS-08 Create JSDoc comment

**Comment by tevin-takata** [comment]
## UserDashboard.jsx

JS-08: Update JSDoc comment

## IndividualsInNeedOfService.jsx:

JS-08: Make JSDoc comment

**Comment by kairemUH** [comment]
## UserDashboard.jsx:

JS-08: Add a JSDoc comment describing page

## IndividualsInNeedOfService.jsx:

JS-08: Same. Add jsdoc comment
