### ISSUE TITLE
Review: Serve the Community and Make A Request

### ISSUE THREAD

**Issue by sanehirakenji** [volunthree/volunthree#132]
## Review Branch

review-serve-and-make

## Files to review

* ServeTheCommunity.jsx
* MakeARequest.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

4/15/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by tevin-takata** [comment]
## ServeTheCommunity.jsx

JS-08: Add JSDoc

## MakeARequest.jsx

JS-08: Add JSDoc

**Comment by sanehirakenji** [comment]
ServeTheCommunity.jsx:
- JS-08: Create a JSDoc comment for this page.

MakeARequest.jsx:
- JS-08: Create a JSDoc comment for this page.

**Comment by kairemUH** [comment]
## ServeTheCommunity.jsx:
JS-08: Add JSDoc comment describing the page.

## MakeARequest.jsx:
JS-08: Same. Add a JSDoc comment for page.

**Comment by tylerz1443** [comment]
## ServeTheCommunity.jsx
- JS-08: Add JSDoc comment

## MakeARequest.jsx:
- JS-08: Same. Add a JSDoc comment

**Comment by jgaleria** [comment]
ServeTheCommunity.jsx
- JS-08: Add JSDoc comment

MakeARequest.jsx: 
- JS-08: Add JSDoc comment

**Comment by ian-lastname** [comment]
### ServeTheCommunity.jsx
- JS-08: Add JSDoc comment

### MakeARquest.jsx
- JS-08: Add JSDoc comment
