### ISSUE TITLE
Review: Landing and About Us

### ISSUE THREAD

**Issue by sanehirakenji** [volunthree/volunthree#51]
## Review Branch

review-landing-and-about-us

## Files to review

* Landing.jsx
* AboutUs.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

1/29/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by sanehirakenji** [comment]
Kenji Sanehira Review Notes:
Landing.jsx
Design-01: Some refactoring can be done to make the 3 columns more readable.
Design-08: Similar to design-01, the three columns can be condensed.
AboutUs.jsx
N/A: For the current contents of the page looks fine for now, just need to add appropriate images.

**Comment by ian-lastname** [comment]
AboutUs.jsx:
Nothing wrong, just have to add actual images in place of the place holders.

Landing.jsx:
Looks alright, though code could be a bit more readable. However, not the end of the world.

**Comment by austindang67** [comment]
AboutUs.jsx:
Good to go.
Landing.jsx
Also good to go.

**Comment by jgaleria** [comment]
AboutUs.jsx: 
Looks good. Just be sure to take out the comments that are labeled To Do. Maybe we can add those in the related issue. 
Formatting is good. Correct use of arrow function. 

Landing.jsx: 
Looks good. Maybe break the paragraphs into new lines.

**Comment by sanehirakenji** [comment]
Final Review Notes:

Landing.jsx:
Design-01: Refactor cards, use CSS for image.
- Code could be more readable.
- Break paragraphs into new lines.
AboutUs.jsx:
Design-01: Use CSS for image.
- Add Image instead of placeholders.
- Change TODO comments into issues.

These will be refactored into a new issue in the M2 project board.
