### ISSUE TITLE
Review: Volunteer Calendar and Forgot Password Pages

### ISSUE THREAD

**Issue by sanehirakenji** [volunthree/volunthree#61]
## Review Branch

review-calendar-and-forgot-pass

## Files to review

* VolunteerCalendar.jsx
* Forgot.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

2/5/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by sanehirakenji** [comment]
VolunteerCalendar.jsx:

- Design-01: Dropdown items can be refactored into smaller components that can be repeated for readability.
- Design-05: Comments underneath the dropdown menus are not very descriptive and can be changed to fit better.
- REACT-01: Can break the dropdowns into components.

Forgot.jsx:

- Design-05: There are no comments in the file. It could potentially benefit from a comment describing what this page is for.

**Comment by ian-lastname** [comment]
Forgot.jsx:
- [ ] D-05: Add some comments explaining what the page is for and maybe how it'll accomplish it.


VolunteerCalender.jsx:
- [ ] R-01: Could just create component for the dropdowns if components are what I think they are.
- [ ] D-05: Add a comment explaining what this page is for.
- [ ] Pretty good otherwise.

**Comment by austindang67** [comment]
VolunteerCalendar.jsx

- Design-05: Some comments necessary to explain the purpose of the page.
- React-01: Making the dropdowns into a component would help on readability and saving time esp if we intend on using more

Forgot.jsx
- Design-05: Just a comment to explain the page.

Looks good!

**Comment by tylerz1443** [comment]
Forgot.jsx
- Design-05: basic page explanations comments are needed.  

VolunteerCalendar.jsx
- Design-05: basic page explanations comments are needed.  
- React-01: dropdown as a component would help updating it and if it will be used on other parts of the site.

**Comment by kairemUH** [comment]
## VolunteerCalendar.jsx

- Design-05: Bare minimum should have comments explaining page and bonus for some of the code.
- JS-08: Should have page explanation and/or function comments be compatible with jsdocs.
- As others have stated, turning the dropdown into a component could be nice if it will be reused.

## Forgot.jsx

- Design-05: Same as for volunteercalender.jsx.
- JS-08: Should have page explanation and/or function comments compatible with jsdocs.

**Comment by jgaleria** [comment]
VolunteerCalendar.jsx
- Design-05: Include more comments explaining the page, specifically when defining the constants
- Design-01: There's 2 instances of Dropdowns in which we can add organizations as needed. Maybe we could create a separate component for this

Forgot.jsx
- Design-05: Include more comments explaining the page

**Comment by sanehirakenji** [comment]
2/5 Review Summary:

VolunteerCalendar.jsx:
- Design-01: Dropdown items can be refactored into smaller components that can be repeated for readability.
- Design-05: Comments underneath the dropdown menus are not very descriptive and can be changed to fit better. Add a comment explaining what this page is for.
- REACT-01: Can break the dropdowns into components.
- JS-08: Should have page explanation and/or function comments be compatible with jsdocs.


Forgot.jsx:
- Design-05: There are no comments in the file. It could potentially benefit from a comment describing what this page is for.
- JS-08: Should have page explanation and/or function comments compatible with jsdocs.
