### ISSUE TITLE
Review: Volunteer Report and Navbar Files

### ISSUE THREAD

**Issue by sanehirakenji** [volunthree/volunthree#73]
## Review Branch

review-report-and-navbar

## Files to review

* Report.jsx
* NavBar.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

2/12/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ian-lastname** [comment]
Report.jsx:
- Looks good so far, can't really find anything that needs fixing.

NavBar.jsx:
- Can't really find anything that needs fixing either. While unnecessary, a comment explaining what the file does could be added (for D-05)

**Comment by kairemUH** [comment]
## Report.jsx

D-05: Add a comment (jsdoc compatible) that has a quick explanation on the purpose and functionality of the page

## NavBar.jsx

 D-05: Same as report.jsx
 
 Overall both files look great!

**Comment by sanehirakenji** [comment]
Report.jsx:
- JS-08: Add Javadoc comments.
- ESLINT-01: Fix the ESLint errors on line 29.

NavBar.jsx:

- Arch-01: File and overarching function can be renamed to “Navbar” and “Navbar.jsx”
- Design-05: Delete the current TODO comment and then add jsdoc appropriate comments that describe the file’s contents.
- JS-01: Similar to the comment above, fix the naming.
- JS-08: Add a jsdoc based comment to change the file.

**Comment by tylerz1443** [comment]
Navbar.jsx
JS-08: add javadoc base comment

Report.jsx
JS-08: add javadoc  comments

**Comment by sanehirakenji** [comment]
Final Review Notes:
Report.jsx:

JS-08: Add Javadoc comments.
ESLINT-01: Fix the ESLint errors on line 29.
NavBar.jsx:

Arch-01: File and overarching function can be renamed to “Navbar” and “Navbar.jsx”
Design-05: Delete the current TODO comment and then add jsdoc appropriate comments that describe the file’s contents.
JS-01: Similar to the comment above, fix the naming.
JS-08: Add a jsdoc based comment to change the file.
