### ISSUE TITLE
Review: Volunteer Opportunities and Volunteer Event

### ISSUE THREAD

**Issue by tevin-takata** [volunthree/volunthree#78]
## Review Branch

review-volunteer-opportunities-and-volunteer-event

## Files to review

* VolunteerOpportunities.jsx
* VolunteerEvent.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

2/19/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by tevin-takata** [comment]
##VolunteerOpportunities.jsx

Looks good.

##VolunteerEvent.jsx

Design-05: Fix unnecessary comment on line 6. Also add comments to describe page.

**Comment by tylerz1443** [comment]
**VolunteerEvent.jsx**
- Design-05: change the stuff ref in the javadoc comment.  comment to describe the items in the list

**VolunteerOpportunities.jsx**
- Design-05: Add doc javadoc comment

**Comment by sanehirakenji** [comment]
VolunteerOpportunities.jsx:
- Design-01: Pagination can be refactored into a component.
- Design-05: Can use a Javadoc comment.
- JS-08: Include JSDoc comments.

VolunteerEvent.jsx:
- Design-05: Comment incorrectly describes “Stuff” when it should describe the volunteer event. Could also use a JavaDoc Comment.
- Design-07: The beginning column can be changed into a component for easier readability.
- JS-08: Include JSDoc comments.

**Comment by jgaleria** [comment]
VolunteerEvent.jsx
- Design-05: Comment refers to <StuffItem>
- Replace placeholders text later on

VolunteerOpportunities.jsx
- Design-01: Pagination.Item is repetitive. Can make a component for it. 
- Design-05: Add javadoc comment. 
- Just need to fill in actual data later on.

**Comment by ian-lastname** [comment]
VolunteerOpportunites.jsx:
- D-05: Create javadoc comment'
- D-01: Could create component for Pagination

VolunteerEvent.jsx:
- D-05: Change stuff reference in the javadoc comment to the name of the actual reference

**Comment by kairemUH** [comment]
## VolunteerEvent.jsx:

- Design-05: Comment still has 'stuff' in it.
- Placeholder text would eventually need to be replaced with a passed in doc.

## VolunteerOpportunites.jsx:

- Design-05: Add jsdoc comment describing page.
