### ISSUE TITLE
Review: Volunteer Organizations and Direct Messaging

### ISSUE THREAD

**Issue by sanehirakenji** [volunthree/volunthree#98]
## Review Branch

review-organizations-and-direct-messaging

## Files to review

* VolunteerOrganizations.jsx
* DirectMessaging.jsx

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)

## Due date

2/26/2024 @ 10:30 am

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by sanehirakenji** [comment]
VolunteerOrganizations.jsx:
Design:
- Design-01: As stated in previous reviews, Pagination can be refactored.
- Design-05: Needs Javadoc Comments

JS:
- JS-08: Needs JSDoc Comments


Direct Messaging.jsx:
JS:
- JS-07: Remove the unnecessary console.log in the submit function.
- JS-08: Needs JSDoc Comments

**Comment by tevin-takata** [comment]
## VolunteerOrganizations.jsx:

Design-05: Add Javadoc comments
JS-08: Use Javadoc comments

## DirectMessaging.jsx:

JS-07: Remove console.log at line 10.

**Comment by austindang67** [comment]
VolunteerOrganizations.jsx:
- Design-05: Just needs some comments.

DirectMessagine.jsx:
- Javascript-06: Remove console.log in line 10, otherwise good.

**Comment by tylerz1443** [comment]
**VolunteerOrganizations.jsx**
- Design-05: needs javadoc comments

**Direct Messaging.jsx**
- JS-07: remove console.log

**Comment by kairemUH** [comment]
## VolunteerOrganizations.jsx

JS-08: Add Javadoc comment explaining file

## DirectMessaging.jsx

JS-07: Remove console.log on line 10

JS-08: Add Javadoc comment explaining file

**Comment by ian-lastname** [comment]
**VolunteeringOrganizations.jsx**
- JS-08: Add Javadoc comment explaining the file
- D-05: Add some comments

**DirectMessaging.jsx**
- JS-07: Remove console.log on line 10 (sorry, forgot to do that)
- JS-08: Add Javadoc comment that explains file

**Comment by jgaleria** [comment]
VolunteerOrganization.jsx: 
- JS-08: Add Javadoc comment for file

DirectMessaging.jsx: 
- JS-08: Add Javadoc comment for file
- JS -07: Remove console.log line 10
